global:
  updateInterval: 60
  nearbyRadius: 10

layers:
  keys:
    - "shops"
  shops:
    world_name: "world"
    key: "default_layer_key"
    label: "default_layer_label"
    updateInterval: 60
    showControls: true
    defaultHidden: false
    priority: 100
    zIndex: 100
    markerFile: "marker.json"
    nearbyRadius: 10
    marker:
      pattern: "<center><b>{title}</b><br><i>{description}</i></center>"
      max_name_length: 40
      max_desc_length: 100
      default_image: "marker-icon"
      size:
        x: 32
        z: 32
      offset:
        x: 0
        z: 0