name: MapMarkers
version: '${project.version}-${git.commit.id.abbrev}'
main: me.lucthesloth.mapmarkers.MapMarkers
api-version: '1.20'
author: LucTheSloth
website: https://ko-fi.com/lucthesloth
depend:
  - Pl3xMap
commands:
  mapmarkers:
    description: MapMarkers command
    aliases: [marker, dominionmarker, dmarker]
  markersmigrate:
    description: Migrate markers from old plugin
    aliases: [mmigrate, dominionmarkersmigrate, dmigrate]